### ISSUE TITLE
Implement search autocomplete

### ISSUE THREAD

**Issue by iamsaquib8** [SupratikRulz/covid-19-reporter#2]
A Search auto-completer feature for users to interact with COVID-19 data and also to increase user experience.

**Comment by SupratikRulz** [comment]
Need to generate a list of country names that are accepted by the API. For few countries we need to build a map like:
- United States -> US
- UK -> United Kingdom
- South Korea -> Korea, South
etc.

The map can be built in frontend for faster execution and the number of countries (195) being static.
@IamSaquib can you create a PR for this?

**Comment by iamsaquib8** [comment]
Sure will work on this!

**Comment by iamsaquib8** [comment]
@SupratikRulz  create a map or just an array with the different possible country names and use some react autocomplete library to filter out from that array?

**Comment by SupratikRulz** [comment]
> @SupratikRulz create a map or just an array with the different possible country names and use some react autocomplete library to filter out from that array?

Yes you can do that
