### ISSUE TITLE
Cite sources

### ISSUE THREAD

**Issue by Hexstream** [SupratikRulz/covid-19-reporter#4]
Nice initiative.

In this era of omnipresent Fake News™, most *sane* users would probably want to at least see a link to where the statistics are pulled from so that they can verify the information themselves if they wish. I'm guessing for many people this would be a hard requirement to be able to take this app seriously.

**Comment by SupratikRulz** [comment]
@Hexstream Thanks for your feedback, yes I agree to your point. Will update this with sources.

**Comment by SupratikRulz** [comment]
@Hexstream This has been fixed in new version hence closing the issue. Thank you for your feedback.

**Comment by Hexstream** [comment]
That was quick! Thank you.
